version: "3.2"
services:
    tblog_mariadb:
        image: centos/mariadb-103-centos7
        ports:
            - "3310:3306"
        restart: always
        environment:
            MYSQL_DATABASE: tblog
            MYSQL_USER: rw_tblog
            MYSQL_PASSWORD: ${MARIADB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MARIADB_PASSWORD}
        volumes:
            - ./99-custom.cnf:/etc/my.cnf.d/99-custom.cnf:Z
            - tblog_mariadb_data:/var/lib/mysql/data:Z
            - tblog_mariadb_logs:/var/lib/mysql/log:Z

    tblog_mariadb_admin:
        image: phpmyadmin:5.1.1
        ports:
            - "3311:80"
        environment:
            PMA_HOST: tblog_mariadb
        restart: always
        links:
            - tblog_mariadb
volumes:
    tblog_mariadb_data:
        external: true
    tblog_mariadb_logs:
        external: true
