# Generated by Django 4.0.1 on 2022-04-15 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tblog_app', '0002_post_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
    ]
