# Generated by Django 4.0.1 on 2022-03-07 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tblog_app', '0003_post_delete_snippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tblog_app.post')),
                ('tag_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tblog_app.tag')),
            ],
        ),
    ]
