# Generated by Django 4.0.1 on 2022-03-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tblog_app', '0004_tag_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_tag',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
