# Generated by Django 4.0.1 on 2022-03-07 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tblog_app', '0005_alter_post_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_tag',
            name='post_id',
            field=models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, to='tblog_app.post'),
        ),
        migrations.AlterField(
            model_name='post_tag',
            name='tag_name',
            field=models.ForeignKey(db_column='tag_name', on_delete=django.db.models.deletion.CASCADE, to='tblog_app.tag'),
        ),
    ]
