# Generated by Django 4.0.1 on 2022-03-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tblog_app', '0006_alter_post_tag_post_id_alter_post_tag_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='tblog_app.Tag'),
        ),
        migrations.DeleteModel(
            name='Post_tag',
        ),
    ]
